# Generated by Django 5.1.3 on 2024-11-30 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_customer_pan_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(default='DEFAULT_PAN', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_customer_name', message='Customer Name must be alphanumeric and cannot contain special characters.', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_product_name', message='Product Name must be alphanumeric and cannot contain special characters.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
